In [1]:
import numpy as np


In [2]:
# Tạo mảng
a = np.array([1,2,3])

# In mảng
print(a)

# In ra 1 phần tử
element = a[1]
print(element)

[1 2 3]
2


In [3]:
# Tạo mảng 2 chiều
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)

# In một phần tử
element = matrix[1, 2]
print(element)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [4]:
# Cách tạo mảng
# Tạo mảng toàn là số 0
a = np.zeros(5)
print(a)

# Tạo mảng toàn là số 1
a = np.ones(5)
print(a)

# Tạo mảng
a = np.empty(5)
print(a)

# Tạo mảng từ 0 đến 100
a = np.arange(100)
print(a)

# Tạo mảng gồm các phần tử với khoảng cách đều nhau
a = np.linspace(0, 10, num=5)
print(a)


# Xác định kiểu dữ liệu
a = np.ones(5, dtype=np.int64)
a

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.   2.5  5.   7.5 10. ]


array([1, 1, 1, 1, 1], dtype=int64)

In [5]:
# Thêm, xóa, sắp xếp mảng

# Tạo mảng ban đầu
arr = np.array([3, 1, 2, 4, 5])
print(arr)

# Sắp xếp
arr = np.sort(arr)
print(arr)

# Sắp xếp ngược
arr = np.sort(arr)[::-1]
print(arr)

# Thêm phần tử vào mảng
arr = np.append(arr, 100)
print(arr)

# Xóa đi một ví trí nào đó trong mảng
arr = np.delete(arr, 3)
print(arr)

[3 1 2 4 5]
[1 2 3 4 5]
[5 4 3 2 1]
[  5   4   3   2   1 100]
[  5   4   3   1 100]


In [6]:
# Tạo một mảng 2 chiều
arr = np.array([[3, 1, 2],
                [4, 6, 8],
                [9, 7, 5]])

sap_xep_theo_hang = np.sort(arr, axis=1) # tăng dần
print(sap_xep_theo_hang)

sap_xep_theo_cot = np.sort(arr, axis=0) # tăng dần
print(sap_xep_theo_cot)

[[1 2 3]
 [4 6 8]
 [5 7 9]]
[[3 1 2]
 [4 6 5]
 [9 7 8]]


In [7]:
# Tạo một mảng 2 chiều
arr = np.array([[3, 1, 2],
                [4, 6, 8],
                [9, 7, 5]])

sap_xep_theo_hang = -np.sort(-arr, axis=1) # giảm dần
print(sap_xep_theo_hang)

sap_xep_theo_cot = -np.sort(-arr, axis=0) # giảm dần
print(sap_xep_theo_cot)

[[3 2 1]
 [8 6 4]
 [9 7 5]]
[[9 7 8]
 [4 6 5]
 [3 1 2]]


In [8]:
# Tạo một mảng 2D
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sử dụng các thuộc tính để lấy thông tin về mảng
so_chieu = arr.ndim  # Số chiều (2 chiều)
kich_thuoc = arr.size  # Kích thước (tổng số phần tử, 6)
hinh_dang = arr.shape  # Hình dạng (số hàng x số cột, (2, 3))

print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)

Số chiều: 2
Kích thước: 6
Hình dạng: (2, 3)


In [9]:
# Chuyển đổi kiểu dữ liệu
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(float)
print(arr_float)

[1. 2. 3. 4. 5.]


In [10]:
# Thay đổi hình dạng của mảng
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [11]:
reshaped_arr = reshaped_arr.flatten() # Chuyển thành mảng 1 chiều
print(reshaped_arr)

[1 2 3 4 5 6]


In [12]:
# Cắt lát mảng
arr = np.array([1, 2, 3, 4, 5])

sub_arr = arr[1:4]  # Cắt từ phần tử thứ 1 đến 4
print(sub_arr) # 2 3 4 5

sub_arr = arr[:-1]  # 1 2 3 4
print(sub_arr)

sub_arr = arr[-2:]  # 4 5 
print(sub_arr)

[2 3 4]
[1 2 3 4]
[4 5]


In [13]:
# Chuyển vị mảng
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# Để chuyển vị mảng, chúng ta có thể sử dụng .T hoặc hàm numpy.transpose().
transposed_arr = arr.T
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [14]:
# Nối mảng
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [15]:
# II. Hàm tính tổng (Sum)
# - Hàm numpy.sum() cho phép tính tổng các phần tử trong mảng.
arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)
print("Tổng của mảng arr:", total)

# III. Hàm tính trung bình (Mean)
# - Hàm numpy.mean() tính giá trị trung bình của các phần tử trong mảng.
average = np.mean(arr)
print("Giá trị trung bình của mảng arr:", average)

# IV. Hàm tìm giá trị lớn nhất và nhỏ nhất (Max và Min)
# - Hàm numpy.max() và numpy.min() dùng để tìm giá trị lớn nhất và nhỏ nhất trong mảng.
max_value = np.max(arr)
min_value = np.min(arr)
print("Giá trị lớn nhất trong mảng arr:", max_value)
print("Giá trị nhỏ nhất trong mảng arr:", min_value)

# V. Hàm tính độ lệch chuẩn (Standard Deviation)
# - Hàm numpy.std() tính độ lệch chuẩn của mảng, đo lường mức độ phân tán của dữ liệu.
std_deviation = np.std(arr)
print("Độ lệch chuẩn của mảng arr:", std_deviation)

# VI. Hàm tính phương sai (Variance)
# - Hàm numpy.var() tính phương sai của mảng, đo lường mức độ biến thiên của dữ liệu.
variance = np.var(arr)
print("Phương sai của mảng arr:", variance)

# VII. Hàm tính tổng tích chập (Dot Product)
# - Hàm numpy.dot() tính tổng tích chập của hai mảng (vector).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print("Tổng tích chập của arr1 và arr2:", dot_product)

Tổng của mảng arr: 15
Giá trị trung bình của mảng arr: 3.0
Giá trị lớn nhất trong mảng arr: 5
Giá trị nhỏ nhất trong mảng arr: 1
Độ lệch chuẩn của mảng arr: 1.4142135623730951
Phương sai của mảng arr: 2.0
Tổng tích chập của arr1 và arr2: 32
